#!/usr/bin/env ruby 

require './string_util'
class Jotter

  def initialize
    puts 'Jot a note...'.gray
    new 
    @entries ||= entries
  end

  def index
    @entries
  end

  def entries
    path = jot_filepath
    Dir.entries(path).each do |entry|
      if File.extname(entry) == '.markdown'
        jot_title(entry)
        file = File.open(path + "/" + entry)
        formatted_line(file)
      end
    end
  end


  def formatted_line(file)
    file.each do |line|
      if line.include?('#')
        hash_index = line.index('#')
        print line[0..hash_index].chop
        hashes = line.scan(/#\w*/)
        hashes.map { |hash| print " " + hash.cyan }
        print "\n"
      else
        puts line.chop
      end
    end
  end

  def jot_title(entry)
    print "\n"
    basename = entry.split('.')[0]
    puts basename
    basename.length.times do
      print '-'
    end
    print '-'
    print "\n"
  end

  def new
    print '=> '.red
    input = gets.chomp
    case input.downcase
      when 'm' || 'menu'  then menu
      when 'i' || 'index' then index
      else create(input)
    end
  end

  def create(input)
    File.open("#{jot_filepath}/#{Time.now.strftime("%F")}.markdown", 'a+') do |jot|
      jot.write "\n"
      jot.write input
    end
    puts 'Saved. Jot another or [M]enu'
    new
  end

  def menu
    commands = {
      d: :delete,
      m: :menu,
      i: :index,
      e: :edit,
      s: :search
    }
    commands.map { |k,option| print option.to_s + " " }
    print "\n"
    print '(menu) '.red
    input = gets.chomp
    send(input)   
  end
 
private

  def jot_filepath
    @filepath ||= File.join(Dir.home, 'Dropbox', 'jots')
  end
end

Jotter.new
